CREATE MEMORY TABLE DATA (ID BIGINT NOT NULL PRIMARY KEY,TEXT VARCHAR(255))
CREATE MEMORY TABLE HIBERNATE_SEQUENCES (SEQUENCE_NAME VARCHAR(255),SEQUENCE_NEXT_HI_VALUE INTEGER)

INSERT INTO DATA VALUES(1,'13dfd66b-105e-42ba-a630-3bd97398e489')
INSERT INTO HIBERNATE_SEQUENCES VALUES('Data',1)
